"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import PasswordField from "./PasswordField";
import { createClient } from "@/lib/supabase/client";
export default function AuthPanel(){
  const router=useRouter();const [tab,setTab]=useState<"login"|"register">("login");const [pass,setPass]=useState("");const [confirm,setConfirm]=useState("");const [status,setStatus]=useState<{type:"success"|"error";text:string}|null>(null);const [loading,setLoading]=useState(false);
  const checks={len:pass.length>=8,upper:/[A-Z]/.test(pass),lower:/[a-z]/.test(pass),num:/\d/.test(pass),special:/[^A-Za-z0-9]/.test(pass)};let score=[checks.len,checks.upper||checks.lower,checks.num,checks.special].filter(Boolean).length;if(!pass)score=0;
  async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setStatus(null);try{const fd=new FormData(e.currentTarget);const supabase=createClient();const {error}=await supabase.auth.signInWithPassword({email:String(fd.get("email")),password:String(fd.get("password"))});if(error)return setStatus({type:"error",text:error.message});router.push("/dashboard");router.refresh()}catch(err){setStatus({type:"error",text:err instanceof Error?err.message:"Inloggen lukt nu niet."})}finally{setLoading(false)}}
  async function register(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus(null);if(pass!==confirm)return setStatus({type:"error",text:"De twee wachtwoorden zijn niet hetzelfde."});if(score<4)return setStatus({type:"error",text:"Kies een sterker wachtwoord voordat je doorgaat."});setLoading(true);try{const fd=new FormData(e.currentTarget);const supabase=createClient();const {error}=await supabase.auth.signUp({email:String(fd.get("email")),password:pass,options:{data:{first_name:String(fd.get("first_name")||""),company:String(fd.get("company")||"")},emailRedirectTo:`${location.origin}/auth/callback`}});if(error)return setStatus({type:"error",text:error.message});setStatus({type:"success",text:"Account aangemaakt. Als e-mailbevestiging aanstaat, krijg je nu een bevestigingsmail."})}catch(err){setStatus({type:"error",text:err instanceof Error?err.message:"Account maken lukt nu niet."})}finally{setLoading(false)}}
  return <div className="authCard reveal"><h1>Welkom.</h1><p>Log in of maak een klantaccount aan.</p><div className="tabs"><button className={`tab ${tab==="login"?"active":""}`} onClick={()=>{setTab("login");setStatus(null)}} type="button">Inloggen</button><button className={`tab ${tab==="register"?"active":""}`} onClick={()=>{setTab("register");setStatus(null)}} type="button">Account maken</button></div>
    <div className={`pane ${tab==="login"?"active":""}`}><form onSubmit={login}><div className="formGrid"><div className="field full"><label htmlFor="login-email">E-mail</label><input id="login-email" name="email" type="email" autoComplete="email" required placeholder="jij@bedrijf.nl"/></div><div className="field full"><label>Wachtwoord</label><PasswordField id="login-password" name="password" placeholder="••••••••" autoComplete="current-password"/></div><div className="field full"><button className="button primary" type="submit" disabled={loading}>{loading?"Bezig…":"Inloggen"} <span className="arrow">→</span></button></div></div></form></div>
    <div className={`pane ${tab==="register"?"active":""}`}><form onSubmit={register}><div className="formGrid"><div className="field"><label htmlFor="first-name">Voornaam</label><input id="first-name" name="first_name" required autoComplete="given-name" placeholder="Voornaam"/></div><div className="field"><label htmlFor="company">Bedrijf</label><input id="company" name="company" autoComplete="organization" placeholder="Bedrijfsnaam"/></div><div className="field full"><label htmlFor="register-email">E-mail</label><input id="register-email" name="email" type="email" required autoComplete="email" placeholder="jij@bedrijf.nl"/></div><div className="field full"><label>Wachtwoord</label><PasswordField id="register-password" name="password" placeholder="Maak een sterk wachtwoord" autoComplete="new-password" onChange={setPass}/><div className="strength" data-level={score}><div className="strengthBars"><i/><i/><i/><i/></div><div className="strengthRow"><span>{["Nog leeg","Zwak","Redelijk","Sterk","Zeer sterk"][score]}</span><span>Wachtwoordsterkte</span></div></div><div className="rules"><div className={`rule ${checks.len?"ok":""}`}>Min. 8 tekens</div><div className={`rule ${checks.upper?"ok":""}`}>Hoofdletter</div><div className={`rule ${checks.lower?"ok":""}`}>Kleine letter</div><div className={`rule ${checks.num?"ok":""}`}>Cijfer</div><div className={`rule ${checks.special?"ok":""}`}>Speciaal teken</div></div></div><div className="field full"><label>Wachtwoord herhalen</label><PasswordField id="confirm-password" name="confirm" placeholder="Nog een keer hetzelfde wachtwoord" autoComplete="new-password" onChange={setConfirm}/></div><div className="field full"><button className="button primary" type="submit" disabled={loading}>{loading?"Bezig…":"Account aanmaken"} <span className="arrow">→</span></button></div></div></form></div>{status&&<div className={`status ${status.type}`}>{status.text}</div>}
  </div>
}
