"use client";
import { useState } from "react";
import CustomSelect from "./CustomSelect";
const projectOptions=[
  {value:"landing",label:"Landing page — €50"},{value:"business",label:"Volledige site + login — €150"},{value:"shop",label:"Webshop — €350"},{value:"custom",label:"API / maatwerk"},{value:"hosting",label:"Hosting"},{value:"maintenance",label:"Onderhoud"}
];
const budgetOptions=[{value:"50-150",label:"€50 – €150"},{value:"150-350",label:"€150 – €350"},{value:"350-750",label:"€350 – €750"},{value:"750+",label:"€750+"},{value:"unknown",label:"Nog niet zeker"}];
export default function ContactForm({defaultProject="landing"}:{defaultProject?:string}){
  const [project,setProject]=useState(projectOptions.some(o=>o.value===defaultProject)?defaultProject:"landing");const [budget,setBudget]=useState("50-150");const [status,setStatus]=useState<{type:"success"|"error";text:string}|null>(null);const [loading,setLoading]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus(null);setLoading(true);const form=new FormData(e.currentTarget);const payload={name:form.get("name"),email:form.get("email"),project,budget,message:form.get("message"),website:form.get("website")};try{const res=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Kon niet versturen");setStatus({type:"success",text:"Gelukt. Je aanvraag staat bij ons binnen. We reageren zo snel mogelijk."});e.currentTarget.reset();setProject("landing");setBudget("50-150")}catch(err){setStatus({type:"error",text:err instanceof Error?err.message:"Er ging iets mis. Mail anders naar info@voidworks.eu."})}finally{setLoading(false)}}
  return <form onSubmit={submit}><input name="website" tabIndex={-1} autoComplete="off" style={{position:"absolute",left:"-9999px"}}/><div className="formGrid"><div className="field"><label htmlFor="name">Naam</label><input id="name" name="name" required autoComplete="name" placeholder="Jouw naam"/></div><div className="field"><label htmlFor="email">E-mail</label><input id="email" name="email" type="email" required autoComplete="email" placeholder="naam@bedrijf.nl"/></div><div className="field"><label>Waar gaat het om?</label><CustomSelect name="project" options={projectOptions} value={project} onChange={setProject} label="Project kiezen"/></div><div className="field"><label>Budget</label><CustomSelect name="budget" options={budgetOptions} value={budget} onChange={setBudget} label="Budget kiezen"/></div><div className="field full"><label htmlFor="message">Wat wil je laten maken?</label><textarea id="message" name="message" required minLength={15} placeholder="Vertel kort wat je bedrijf doet en wat de website moet kunnen. Geen compleet plan nodig."/></div><div className="field full"><button className="button primary" data-magnetic="true" type="submit" disabled={loading}>{loading?"Versturen…":"Aanvraag versturen"} <span className="arrow">↗</span></button></div></div>{status&&<div className={`status ${status.type}`}>{status.text}</div>}</form>
}
